### ISSUE TITLE
finish-CRAN-checklist

### ISSUE THREAD

**Issue by EchoRLiu** [EchoRLiu/robustGarch#26]

**Comment by dan9401** [comment]
Reference links:
1. https://cran.r-project.org/submit.html
2. https://cran.r-project.org/web/packages/submission_checklist.html
3. https://r-pkgs.org/release.html

**Comment by EchoRLiu** [comment]
- [x] The package contains a DESCRIPTION file.
- [x] DESCRIPTION file contains the valid maintainer field "NAME <EMAIL>".
- [ ] You submit a tar.gz created with R CMD build.
- [ ] You are familiar with the rest of the [CRAN policies](https://cran.r-project.org/web/packages/policies.html)
          - [ ] copyright related as in #[37](https://github.com/EchoRLiu/robustGarch/issues/37)

**Comment by dan9401** [comment]
* The github action runs `R CMD check` thru `rcmdcheck()` function with `--as-cran` as default arg: https://github.com/r-lib/actions/blob/v2-branch/check-r-package/action.yaml

**Comment by dan9401** [comment]
Read this section carefully: https://r-pkgs.org/release.html#sec-release-initial. add additional notes regarding the entire article

And a few things to check here: https://github.com/[DavisVaughan/extrachecks](https://github.com/DavisVaughan/extrachecks)

**Comment by dan9401** [comment]
Update: 

I've been experimenting with my own package, after some additional reading, I believe to use [devtools::submit_cran()](https://devtools.r-lib.org/reference/submit_cran.html) is probably the best and easiest choice, as described here in https://r-pkgs.org/release.html#sec-release-process.

Another thing is that, besides `devtools:check()` and the GitHub action checks we have been running, it will be worth it to run `devtools::check_win_devel(), ...` (a series of 3 functions) with winbuilder, which is suppose to be the exact environment that CRAN is using. I did get 3 additional notes that were not flagged previously from them. I'll cover the checks when the time come.
